@extends('layouts.app')
@section('title', 'Gallery')
@section('content')
@php($settings = \App\Models\SchoolSetting::first())
<style>
.gallery-hero{position:relative;min-height:390px;display:flex;align-items:center;background-image:linear-gradient(90deg,rgba(5,38,78,.82),rgba(13,110,253,.35)),url('{{ $settings?->gallery_hero_image ? asset('storage/'.$settings->gallery_hero_image) : ($settings?->home_hero_image ? asset('storage/'.$settings->home_hero_image) : asset('images/school-building.jpg')) }}');background-size:cover;background-position:center;border-bottom:6px solid #ffc107}.gallery-hero-copy{max-width:720px}.gallery-badge{display:inline-block;padding:.5rem 1rem;border-radius:999px;background:rgba(255,255,255,.16);border:1px solid rgba(255,255,255,.32);font-weight:700}.gallery-hero h1{font-size:clamp(2.5rem,5vw,4.4rem);line-height:1.05;letter-spacing:-.025em}.gallery-intro{background:linear-gradient(135deg,#eef7ff,#fffdf5)}.gallery-stat{height:100%;padding:1.35rem;border-radius:20px;background:#fff;box-shadow:0 10px 28px rgba(25,55,90,.07)}.gallery-stat-icon{width:48px;height:48px;border-radius:15px;display:flex;align-items:center;justify-content:center;font-size:1.25rem}.gallery-card{border:0;border-radius:22px;overflow:hidden;background:#fff;box-shadow:0 12px 32px rgba(26,55,91,.09);height:100%;transition:transform .25s ease,box-shadow .25s ease}.gallery-card:hover{transform:translateY(-6px);box-shadow:0 20px 42px rgba(26,55,91,.15)}.gallery-page-frame{height:300px;width:100%;background:linear-gradient(135deg,#f8fbff,#fff);display:flex;align-items:center;justify-content:center;padding:10px;overflow:hidden}.gallery-page-img{width:100%;height:100%;object-fit:contain;object-position:center;display:block;cursor:zoom-in;border-radius:14px;transition:transform .3s ease}.gallery-card:hover .gallery-page-img{transform:scale(1.025)}.gallery-card-body{padding:1.25rem 1.35rem}.gallery-page-lightbox{position:fixed;inset:0;z-index:9999;background:rgba(3,18,36,.94);display:none;align-items:center;justify-content:center;padding:28px}.gallery-page-lightbox.is-open{display:flex}.gallery-page-lightbox img{max-width:95vw;max-height:86vh;width:auto;height:auto;object-fit:contain;border-radius:12px;box-shadow:0 20px 60px rgba(0,0,0,.4)}.gallery-page-close{position:absolute;top:18px;right:24px;width:46px;height:46px;border:0;border-radius:50%;background:#fff;font-size:28px;line-height:1;cursor:pointer}.gallery-page-caption{position:absolute;bottom:16px;left:20px;right:20px;text-align:center;color:#fff;font-weight:600}.gallery-empty{border:2px dashed #d9e6f3;border-radius:24px;background:#fff}.gallery-cta{background:linear-gradient(135deg,#0d6efd,#0752b8);border-radius:26px;color:#fff;overflow:hidden;position:relative}.gallery-cta:after{content:'';position:absolute;width:220px;height:220px;border-radius:50%;background:rgba(255,193,7,.2);right:-70px;bottom:-100px}@media(max-width:767px){.gallery-hero{min-height:330px}.gallery-page-frame{height:300px}.gallery-cta{text-align:center}}
</style>

<section class="gallery-hero text-white"><div class="container py-5"><div class="gallery-hero-copy"><span class="gallery-badge">CAMPUS LIFE</span><h1 class="fw-bold mt-3 mb-3">{{ $settings?->gallery_heading ?: 'Memories from our campus' }}</h1><p class="lead mb-0 opacity-90">{{ $settings?->gallery_subheading ?: 'Explore joyful learning, creativity, celebrations and everyday moments that make school life special.' }}</p></div></div></section>

<section class="py-5 gallery-intro"><div class="container py-lg-3"><div class="row align-items-center g-4"><div class="col-lg-6"><span class="text-primary fw-bold">LIFE AT C-NET PATHSHALA</span><h2 class="display-6 fw-bold mt-2">Learning is more than books.</h2><p class="lead text-secondary mb-0">Our gallery brings together classroom activities, creativity, celebrations and the happy moments children share while learning and growing together.</p></div><div class="col-lg-6"><div class="row g-3"><div class="col-6"><div class="gallery-stat"><div class="gallery-stat-icon bg-primary bg-opacity-10 text-primary mb-3"><i class="fa-solid fa-book-open-reader"></i></div><h5 class="fw-bold">Joyful Learning</h5><p class="text-secondary small mb-0">Curiosity, participation and discovery in everyday school life.</p></div></div><div class="col-6"><div class="gallery-stat"><div class="gallery-stat-icon bg-warning bg-opacity-25 text-warning mb-3"><i class="fa-solid fa-palette"></i></div><h5 class="fw-bold">Creative Moments</h5><p class="text-secondary small mb-0">Activities and experiences that help every child express and grow.</p></div></div></div></div></div></div></section>

<section class="py-5 bg-light"><div class="container py-lg-3"><div class="text-center mb-5"><span class="text-primary fw-bold">SCHOOL GALLERY</span><h2 class="display-6 fw-bold mt-2">Moments worth remembering</h2><p class="text-secondary mx-auto" style="max-width:680px">Click any photograph to view it in full size.</p></div><div class="row g-4">@forelse($galleries ?? [] as $gallery)<div class="col-sm-6 col-lg-4"><div class="gallery-card"><div class="gallery-page-frame"><img src="{{ asset('storage/'.$gallery->image) }}" alt="{{ $gallery->title ?? 'School gallery' }}" class="gallery-page-img" data-full-image="{{ asset('storage/'.$gallery->image) }}" data-caption="{{ $gallery->title ?? 'School Moment' }}"></div><div class="gallery-card-body"><div class="d-flex align-items-start gap-3"><div class="gallery-stat-icon bg-primary bg-opacity-10 text-primary flex-shrink-0"><i class="fa-regular fa-image"></i></div><div><h5 class="mb-1 fw-bold">{{ $gallery->title ?? 'School Moment' }}</h5>@if(!empty($gallery->description))<p class="text-secondary small mb-0">{{ $gallery->description }}</p>@else<p class="text-secondary small mb-0">A special moment from C-Net Pathshala.</p>@endif</div></div></div></div></div>@empty<div class="col-12"><div class="gallery-empty text-center py-5 px-3"><div class="gallery-stat-icon bg-primary bg-opacity-10 text-primary mx-auto mb-3"><i class="fa-regular fa-images"></i></div><h4 class="fw-bold">No gallery images yet</h4><p class="text-secondary mb-0">School memories will appear here as images are added from the Admin Panel.</p></div></div>@endforelse</div></div></section>

<section class="py-5"><div class="container"><div class="gallery-cta p-4 p-lg-5"><div class="row align-items-center position-relative" style="z-index:1"><div class="col-lg-8"><span class="text-warning fw-bold">GROW • LEARN • SHINE</span><h2 class="fw-bold mt-2 mb-2">Every school day creates a new memory.</h2><p class="mb-lg-0 opacity-90">A caring environment where children learn with confidence, friendship and joy.</p></div><div class="col-lg-4 text-lg-end mt-3 mt-lg-0"><a href="{{ url('/admission') }}" class="btn btn-warning btn-lg rounded-pill px-4 fw-bold">Explore Admissions</a></div></div></div></div></section>

<div class="gallery-page-lightbox" id="galleryPageLightbox"><button type="button" class="gallery-page-close" id="galleryPageClose">&times;</button><img id="galleryPageImage" src="" alt=""><div class="gallery-page-caption" id="galleryPageCaption"></div></div>
<script>
document.addEventListener('DOMContentLoaded',function(){const l=document.getElementById('galleryPageLightbox'),i=document.getElementById('galleryPageImage'),c=document.getElementById('galleryPageCaption'),b=document.getElementById('galleryPageClose');function close(){l.classList.remove('is-open');i.src='';document.body.style.overflow=''}document.querySelectorAll('.gallery-page-img').forEach(function(x){x.addEventListener('click',function(){i.src=x.dataset.fullImage;i.alt=x.alt||'';c.textContent=x.dataset.caption||'';l.classList.add('is-open');document.body.style.overflow='hidden'})});b.addEventListener('click',close);l.addEventListener('click',function(e){if(e.target===l)close()});document.addEventListener('keydown',function(e){if(e.key==='Escape')close()})});
</script>
@endsection
