@extends('admin.layouts.app')
@section('title','Attendance')
@section('heading','Attendance')
@section('content')
<div class="d-flex flex-wrap justify-content-between align-items-end gap-3 mb-4"><div><h1 class="fw-bold mb-1">Daily Attendance</h1><p class="text-secondary mb-0">Mark Present, Absent or Leave for active students.</p></div></div>
@if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
@if($errors->any())<div class="alert alert-danger">Please check the attendance entries and try again.</div>@endif
<div class="card border-0 shadow-sm mb-4"><div class="card-body"><form method="GET" action="{{ route('admin.attendance.index') }}" class="row g-2"><div class="col-md-3"><label class="form-label">Date</label><input type="date" name="date" value="{{ $date }}" class="form-control"></div><div class="col-md-6"><label class="form-label">Search Student</label><input type="search" name="q" value="{{ $search }}" class="form-control" placeholder="Admission number or student name"></div><div class="col-md-3 d-flex align-items-end gap-2"><button class="btn btn-primary flex-fill">Search</button>@if($search !== '')<a href="{{ route('admin.attendance.index',['date'=>$date]) }}" class="btn btn-outline-secondary">Clear</a>@endif</div></form></div></div>
<form method="POST" action="{{ route('admin.attendance.store') }}">@csrf<input type="hidden" name="attendance_date" value="{{ $date }}"><div class="card border-0 shadow-sm"><div class="card-body p-4"><div class="d-flex justify-content-between align-items-center mb-3"><h5 class="fw-bold mb-0">Attendance for {{ \Carbon\Carbon::parse($date)->format('d M Y') }}</h5><button type="button" class="btn btn-sm btn-outline-success" onclick="document.querySelectorAll('.status-select').forEach(s=>s.value='Present')">Mark All Present</button></div><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Student</th><th>Admission No.</th><th>Class / Section</th><th style="width:170px">Status</th><th>Remark</th></tr></thead><tbody>@forelse($students as $student)@php($row=$attendance->get($student->id))<tr><td><strong>{{ $student->user->name }}</strong></td><td>{{ $student->admission_no }}</td><td>{{ $student->class_name ?: '—' }}{{ $student->section ? ' / '.$student->section : '' }}</td><td><select name="attendance[{{ $student->id }}][status]" class="form-select status-select">@foreach(['Present','Absent','Leave'] as $status)<option value="{{ $status }}" @selected(($row?->status ?? 'Present')===$status)>{{ $status }}</option>@endforeach</select></td><td><input type="text" name="attendance[{{ $student->id }}][remark]" value="{{ $row?->remark }}" class="form-control" placeholder="Optional remark"></td></tr>@empty<tr><td colspan="5" class="text-center text-secondary py-4">No active students found.</td></tr>@endforelse</tbody></table></div>@if($students->isNotEmpty())<div class="text-end mt-3"><button class="btn btn-primary px-4" type="submit"><i class="fa-solid fa-floppy-disk me-1"></i> Save Attendance</button></div>@endif</div></div></form>
@endsection
