---
deployment:
  tasks:
    - export APPPATH=/home4/mcied45x/repositories/senet-pathshala
    - cd $APPPATH && /opt/cpanel/ea-php83/root/usr/bin/php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
    - cd $APPPATH && /opt/cpanel/ea-php83/root/usr/bin/php composer-setup.php --install-dir=$APPPATH --filename=composer.phar
    - cd $APPPATH && /opt/cpanel/ea-php83/root/usr/bin/php composer.phar install --no-dev --optimize-autoloader --no-interaction
    - cd $APPPATH && mkdir -p storage/framework/cache storage/framework/sessions storage/framework/views storage/logs bootstrap/cache
    - cd $APPPATH && /opt/cpanel/ea-php83/root/usr/bin/php artisan migrate --force
    - cd $APPPATH && /opt/cpanel/ea-php83/root/usr/bin/php artisan config:clear
    - cd $APPPATH && /opt/cpanel/ea-php83/root/usr/bin/php artisan config:cache
    - cd $APPPATH && /opt/cpanel/ea-php83/root/usr/bin/php artisan route:cache
    - cd $APPPATH && /opt/cpanel/ea-php83/root/usr/bin/php artisan view:cache
    - cd $APPPATH && rm -f composer-setup.php composer.phar
