@extends('admin.layouts.app')
@section('title', 'Notices')
@section('heading', 'Notices')
@section('content')
<div class="d-flex flex-wrap justify-content-between align-items-center gap-3 mb-4"><div><h1 class="fw-bold">Notices</h1><p class="text-secondary mb-0">Publish and manage school announcements campus-wise.</p></div><form method="GET" class="d-flex gap-2"><select name="branch_id" class="form-select"><option value="">All Campuses</option>@foreach($branches as $branch)<option value="{{ $branch->id }}" @selected((string)request('branch_id')===(string)$branch->id)>{{ $branch->name }}</option>@endforeach</select><button class="btn btn-outline-primary">Filter</button></form></div>
@if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
<div class="card border-0 shadow-sm mb-4"><div class="card-body"><h5>Add Notice</h5><form action="{{ route('admin.notices.store') }}" method="POST" class="row g-3">@csrf<div class="col-md-4"><label class="form-label">Campus</label><select name="branch_id" class="form-select"><option value="">All Campuses</option>@foreach($branches as $branch)<option value="{{ $branch->id }}" @selected((string)old('branch_id')===(string)$branch->id)>{{ $branch->name }}</option>@endforeach</select><div class="form-text">Leave as All Campuses for a school-wide notice.</div></div><div class="col-md-4"><label class="form-label">Title</label><input name="title" value="{{ old('title') }}" class="form-control" required></div><div class="col-md-2"><label class="form-label">Date</label><input type="date" name="notice_date" value="{{ old('notice_date',now()->format('Y-m-d')) }}" class="form-control" required></div><div class="col-md-2"><label class="form-label">Status</label><select name="status" class="form-select"><option value="1">Published</option><option value="0">Draft</option></select></div><div class="col-12"><label class="form-label">Description</label><textarea name="description" rows="3" class="form-control">{{ old('description') }}</textarea></div><div class="col-12"><button class="btn btn-primary">Publish Notice</button></div></form></div></div>
<div class="card border-0 shadow-sm"><div class="card-body"><h5 class="mb-3">Existing Notices</h5><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Title</th><th>Campus</th><th>Date</th><th>Status</th><th class="text-end">Action</th></tr></thead><tbody>@forelse($notices as $notice)<tr><td><strong>{{ $notice->title }}</strong><div class="small text-secondary">{{ $notice->description }}</div></td><td>{{ $notice->branch?->name ?: 'All Campuses' }}</td><td>{{ $notice->notice_date?->format('d M Y') }}</td><td><span class="badge {{ $notice->status ? 'bg-success' : 'bg-secondary' }}">{{ $notice->status ? 'Published' : 'Draft' }}</span></td><td class="text-end"><button type="button" class="btn btn-sm btn-outline-primary" data-bs-toggle="modal" data-bs-target="#editNotice{{ $notice->id }}">Edit</button> <form class="d-inline" action="{{ route('admin.notices.destroy', $notice) }}" method="POST" onsubmit="return confirm('Delete this notice?')">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger">Delete</button></form></td></tr>@empty<tr><td colspan="5" class="text-center text-secondary py-4">No notices yet.</td></tr>@endforelse</tbody></table></div>{{ $notices->links() }}</div></div>
@foreach($notices as $notice)
<div class="modal fade" id="editNotice{{ $notice->id }}" tabindex="-1" aria-hidden="true"><div class="modal-dialog modal-lg"><div class="modal-content"><div class="modal-header"><h5 class="modal-title">Edit Notice</h5><button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button></div><form action="{{ route('admin.notices.update', $notice) }}" method="POST">@csrf @method('PUT')<div class="modal-body"><div class="row g-3"><div class="col-md-4"><label class="form-label">Campus</label><select name="branch_id" class="form-select"><option value="">All Campuses</option>@foreach($branches as $branch)<option value="{{ $branch->id }}" @selected((string)$notice->branch_id===(string)$branch->id)>{{ $branch->name }}</option>@endforeach</select></div><div class="col-md-4"><label class="form-label">Title</label><input name="title" value="{{ $notice->title }}" class="form-control" required></div><div class="col-md-2"><label class="form-label">Date</label><input type="date" name="notice_date" value="{{ $notice->notice_date?->format('Y-m-d') }}" class="form-control" required></div><div class="col-md-2"><label class="form-label">Status</label><select name="status" class="form-select"><option value="1" @selected($notice->status)>Published</option><option value="0" @selected(!$notice->status)>Draft</option></select></div><div class="col-12"><label class="form-label">Description</label><textarea name="description" rows="4" class="form-control">{{ $notice->description }}</textarea></div></div></div><div class="modal-footer"><button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button><button class="btn btn-primary">Save Changes</button></div></form></div></div></div>
@endforeach
@endsection
