@extends('admin.layouts.app')
@section('title', 'Bulk ID Cards')
@section('heading', 'Bulk ID Cards')
@section('content')
<div class="mb-4"><h1 class="fw-bold">Bulk ID Card Print</h1><p class="text-secondary mb-0">Filter by campus, class and section, then select one student, selected students, or the whole filtered class for bulk printing.</p></div>
@if($errors->any())<div class="alert alert-danger">{{ $errors->first() }}</div>@endif
<div class="card border-0 shadow-sm mb-4"><div class="card-body"><form method="GET" action="{{ route('admin.student-id-cards.index') }}" class="row g-2"><div class="col-md-3"><label class="form-label">Campus</label><select name="branch_id" id="branchSelect" class="form-select"><option value="">All Campuses</option>@foreach($branches as $branch)<option value="{{ $branch->id }}" @selected((string)$branchId===(string)$branch->id)>{{ $branch->name }}</option>@endforeach</select></div><div class="col-md-3"><label class="form-label">Class</label><select name="class_name" id="classSelect" class="form-select"><option value="">All Classes</option>@foreach($classes as $class)<option value="{{ $class->name }}" data-branch="{{ $class->branch_id }}" data-sections='@json($class->section_list)' @selected($className===$class->name)>{{ $class->name }}</option>@endforeach</select></div><div class="col-md-2"><label class="form-label">Section</label><select name="section" id="sectionSelect" class="form-select"><option value="">All Sections</option>@foreach($sections as $s)<option value="{{ $s }}" @selected($section===$s)>{{ $s }}</option>@endforeach</select></div><div class="col-md-2"><label class="form-label">Search Student</label><input type="search" name="q" value="{{ $search }}" class="form-control" placeholder="Admission / name"></div><div class="col-md-2 d-flex align-items-end gap-2"><button class="btn btn-primary flex-fill">Filter</button>@if($search !== '' || $branchId || $className !== '' || $section !== '')<a href="{{ route('admin.student-id-cards.index') }}" class="btn btn-outline-secondary">Clear</a>@endif</div></form></div></div>
<form method="POST" action="{{ route('admin.student-id-cards.print') }}" target="_blank">@csrf
<div class="card border-0 shadow-sm"><div class="card-body p-4">
<div class="d-flex flex-wrap justify-content-between align-items-center gap-2 mb-3"><div><button type="button" id="select-all" class="btn btn-outline-primary btn-sm">Select All Filtered Students</button><button type="button" id="clear-selection" class="btn btn-outline-secondary btn-sm ms-1">Clear Selection</button></div><span class="text-secondary small">Up to 100 students can be printed in one batch.</span></div>
<div class="table-responsive"><table class="table align-middle"><thead><tr><th style="width:60px"><input id="master-check" class="form-check-input" type="checkbox" title="Select all"></th><th>Student</th><th>Admission No.</th><th>Campus</th><th>Class / Section</th><th>Roll No.</th></tr></thead><tbody>
@forelse($students as $student)<tr><td><input class="form-check-input student-check" type="checkbox" name="students[]" value="{{ $student->id }}"></td><td class="fw-semibold">{{ $student->user->name }}</td><td>{{ $student->admission_no }}</td><td>{{ $student->branch?->name ?: '—' }}</td><td>{{ $student->class_name ?: '—' }} {{ $student->section ? '/ '.$student->section : '' }}</td><td>{{ $student->roll_no ?: '—' }}</td></tr>@empty<tr><td colspan="6" class="text-center text-secondary py-4">No active students found for the selected filters.</td></tr>@endforelse
</tbody></table></div>
<div class="d-flex justify-content-between align-items-center mt-3"><span id="selected-count" class="text-secondary">0 selected</span><button id="print-btn" class="btn btn-primary" type="submit" disabled>Print Selected ID Cards</button></div>
</div></div></form>
<script>document.addEventListener('DOMContentLoaded',function(){const checks=[...document.querySelectorAll('.student-check')],count=document.getElementById('selected-count'),btn=document.getElementById('print-btn'),master=document.getElementById('master-check'),selectAll=document.getElementById('select-all'),clear=document.getElementById('clear-selection'),branch=document.getElementById('branchSelect'),cls=document.getElementById('classSelect'),section=document.getElementById('sectionSelect');function sync(){const n=checks.filter(x=>x.checked).length;count.textContent=n+' selected';btn.disabled=n<1;btn.textContent=n?('Print '+n+' ID Card'+(n===1?'':'s')):'Print Selected ID Cards';if(master){master.checked=checks.length>0&&n===checks.length;master.indeterminate=n>0&&n<checks.length}}function setAll(value){checks.forEach(x=>x.checked=value);sync()}function loadSections(){const opt=cls.options[cls.selectedIndex];let list=[];try{list=JSON.parse(opt?.dataset?.sections||'[]')}catch(e){}const current=@json($section);section.innerHTML='<option value="">All Sections</option>';list.forEach(v=>{const o=document.createElement('option');o.value=v;o.textContent=v;if(v===current)o.selected=true;section.appendChild(o)})}branch.addEventListener('change',function(){cls.value='';section.value=''});cls.addEventListener('change',loadSections);checks.forEach(x=>x.addEventListener('change',sync));master?.addEventListener('change',()=>setAll(master.checked));selectAll?.addEventListener('click',()=>setAll(true));clear?.addEventListener('click',()=>setAll(false));sync();loadSections();});</script>
@endsection
