@extends('admin.layouts.app')
@section('title','Learning Programs')
@section('heading','Learning Programs CMS')
@section('content')
<div class="mb-4"><h1 class="fw-bold">Learning Programs</h1><p class="text-secondary">Home Page cards और program detail pages यहीं से manage करें. Add, Edit, Show/Hide, Order और Remove सभी controls available हैं.</p></div>
@if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
@if($errors->any())<div class="alert alert-danger"><ul class="mb-0">@foreach($errors->all() as $e)<li>{{ $e }}</li>@endforeach</ul></div>@endif

<details class="card border-0 shadow-sm mb-4"><summary class="card-header bg-white p-3 fw-bold" style="cursor:pointer">+ Add New Learning Program</summary><div class="card-body p-4"><form action="{{ route('admin.programs.store') }}" method="POST" enctype="multipart/form-data">@csrf<div class="row g-3">
<div class="col-md-4"><label class="form-label">Program Name *</label><input class="form-control" name="name" value="{{ old('name') }}" required></div><div class="col-md-4"><label class="form-label">URL Slug</label><input class="form-control" name="slug" value="{{ old('slug') }}" placeholder="example: class-one"><div class="form-text">खाली छोड़ने पर name से automatic बनेगा.</div></div><div class="col-md-2"><label class="form-label">Display Order</label><input type="number" min="0" name="sort_order" class="form-control" value="{{ old('sort_order') }}"></div><div class="col-md-2 d-flex align-items-end"><div class="form-check form-switch mb-2"><input class="form-check-input" type="checkbox" name="is_active" value="1" checked><label class="form-check-label">Show</label></div></div>
<div class="col-md-6"><label class="form-label">Program Image</label><input class="form-control" type="file" name="image" accept="image/*"></div><div class="col-md-6"><label class="form-label">Home Card Short Text</label><input class="form-control" name="card_text" value="{{ old('card_text') }}"></div>
<div class="col-12"><label class="form-label">Detail Page Introduction *</label><textarea class="form-control" name="intro" rows="3" required>{{ old('intro') }}</textarea></div><div class="col-12"><label class="form-label">What Children Learn</label><textarea class="form-control" name="focus" rows="5">{{ old('focus') }}</textarea><div class="form-text">हर learning point नई line में लिखें.</div></div><div class="col-12"><label class="form-label">Learning Approach</label><textarea class="form-control" name="learning_approach" rows="4">{{ old('learning_approach') }}</textarea></div><div class="col-12"><button class="btn btn-success">Add Program</button></div>
</div></form></div></details>

@forelse($programs as $program)
<div class="card border-0 shadow-sm mb-4"><div class="card-body p-4"><form action="{{ route('admin.programs.update',$program) }}" method="POST" enctype="multipart/form-data">@csrf @method('PUT')<div class="d-flex flex-wrap justify-content-between align-items-center gap-2 mb-3"><h4 class="mb-0">{{ $program->name }}</h4><div class="d-flex gap-3 align-items-center"><span class="badge {{ $program->is_active?'bg-success':'bg-secondary' }}">{{ $program->is_active?'Visible':'Hidden' }}</span><div class="form-check form-switch"><input class="form-check-input" type="checkbox" name="is_active" value="1" @checked($program->is_active)><label class="form-check-label">Show on website</label></div></div></div><div class="row g-3">
<div class="col-md-4"><label class="form-label">Program Name</label><input class="form-control" name="name" value="{{ $program->name }}" required></div><div class="col-md-4"><label class="form-label">URL Slug</label><input class="form-control" name="slug" value="{{ $program->slug }}" required></div><div class="col-md-2"><label class="form-label">Display Order</label><input type="number" min="0" name="sort_order" class="form-control" value="{{ $program->sort_order }}"></div><div class="col-md-2"><label class="form-label">Current Image</label><div class="small text-secondary text-truncate">{{ $program->image ?: 'No image' }}</div></div>
<div class="col-md-6"><label class="form-label">Program Image</label><input class="form-control" type="file" name="image" accept="image/*"></div><div class="col-md-6"><label class="form-label">Home Card Short Text</label><input class="form-control" name="card_text" value="{{ $program->card_text }}"></div>
<div class="col-12"><label class="form-label">Detail Page Introduction</label><textarea class="form-control" name="intro" rows="3" required>{{ $program->intro }}</textarea></div><div class="col-12"><label class="form-label">What Children Learn</label><textarea class="form-control" name="focus" rows="6">{{ $program->focus }}</textarea><div class="form-text">हर learning point नई line में लिखें.</div></div><div class="col-12"><label class="form-label">Learning Approach</label><textarea class="form-control" name="learning_approach" rows="4">{{ $program->learning_approach }}</textarea></div><div class="col-12"><button class="btn btn-primary">Save Changes</button></div>
</div></form><hr><form action="{{ route('admin.programs.destroy',$program) }}" method="POST" onsubmit="return confirm('Remove {{ $program->name }} from Learning Programs?')">@csrf @method('DELETE')<button class="btn btn-outline-danger btn-sm">Remove Program</button></form></div></div>
@empty<div class="alert alert-info">No learning programs yet. Use “Add New Learning Program”.</div>@endforelse
@endsection