@extends('admin.layouts.app')
@section('title','Students')
@section('heading','Students')
@section('content')
<div class="d-flex flex-wrap justify-content-between align-items-center gap-3 mb-4"><div><h1 class="fw-bold mb-1">Students</h1><p class="text-secondary mb-0">Manage student records, login details and photos.</p></div><a href="{{ route('admin.students.create') }}" class="btn btn-primary"><i class="fa-solid fa-plus me-1"></i> Add Student</a></div>
@if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
<div class="card border-0 shadow-sm"><div class="card-body p-4"><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Photo</th><th>Student</th><th>Admission No.</th><th>Class</th><th>Roll</th><th>Status</th><th></th></tr></thead><tbody>
@forelse($students as $student)<tr><td>@if($student->photo)<img src="{{ asset('storage/'.$student->photo) }}" alt="" width="48" height="58" class="rounded border" style="object-fit:cover">@else<div class="bg-light border rounded d-flex align-items-center justify-content-center text-secondary" style="width:48px;height:58px;font-size:10px">No Photo</div>@endif</td><td><div class="fw-semibold">{{ $student->user->name }}</div><small class="text-secondary">{{ $student->user->email }}</small></td><td>{{ $student->admission_no }}</td><td>{{ $student->class_name ?: '—' }} {{ $student->section ? '/ '.$student->section : '' }}</td><td>{{ $student->roll_no ?: '—' }}</td><td><span class="badge {{ $student->is_active ? 'bg-success' : 'bg-secondary' }}">{{ $student->is_active ? 'Active' : 'Inactive' }}</span></td><td class="text-end"><div class="d-flex flex-wrap justify-content-end gap-2"><a href="{{ route('admin.students.show',$student) }}" class="btn btn-sm btn-outline-secondary">View</a><a href="{{ route('admin.students.edit',$student) }}" class="btn btn-sm btn-outline-primary">Edit / Photo</a><form method="POST" action="{{ route('admin.students.status',$student) }}" onsubmit="return confirm('{{ $student->is_active ? 'Deactivate this student account?' : 'Activate this student account?' }}')">@csrf @method('PATCH')<button class="btn btn-sm {{ $student->is_active ? 'btn-outline-danger' : 'btn-outline-success' }}" type="submit">{{ $student->is_active ? 'Deactivate' : 'Activate' }}</button></form></div></td></tr>@empty<tr><td colspan="7" class="text-center text-secondary py-4">No students found.</td></tr>@endforelse
</tbody></table></div></div></div>
@endsection
