@extends('admin.layouts.app')
@section('title','Students')
@section('heading','Students')
@section('content')
<div class="d-flex flex-wrap justify-content-between align-items-center gap-3 mb-4"><div><h1 class="fw-bold mb-1">Students</h1><p class="text-secondary mb-0">Manage student records by campus, class and section.</p></div><a href="{{ route('admin.students.create') }}" class="btn btn-primary"><i class="fa-solid fa-plus me-1"></i> Add Student</a></div>
@if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
<div class="card border-0 shadow-sm mb-4"><div class="card-body"><form method="GET" action="{{ route('admin.students.index') }}" class="row g-2"><div class="col-md-4"><label class="form-label">Campus</label><select name="branch_id" class="form-select"><option value="">All Campuses</option>@foreach($branches as $branch)<option value="{{ $branch->id }}" @selected((string)request('branch_id')===(string)$branch->id)>{{ $branch->name }}</option>@endforeach</select></div><div class="col-md-5"><label class="form-label">Search Student</label><input type="search" name="q" value="{{ $search }}" class="form-control" placeholder="Admission number or student name"></div><div class="col-md-3 d-flex align-items-end gap-2"><button class="btn btn-primary flex-fill"><i class="fa-solid fa-magnifying-glass me-1"></i> Search</button>@if($search !== '' || request('branch_id'))<a href="{{ route('admin.students.index') }}" class="btn btn-outline-secondary">Clear</a>@endif</div></form></div></div>
<div class="card border-0 shadow-sm mb-4"><div class="card-body p-4"><h5 class="fw-bold mb-3"><i class="fa-solid fa-file-export text-success me-2"></i>Campus / Classwise Student List</h5><form method="GET" action="{{ route('admin.students.class-report') }}" target="_blank"><div class="row g-3"><div class="col-md-3"><label class="form-label">Campus</label><select name="branch_id" class="form-select"><option value="">All Campuses</option>@foreach($branches as $branch)<option value="{{ $branch->id }}">{{ $branch->name }}</option>@endforeach</select></div><div class="col-md-3"><label class="form-label">Class *</label><select name="class_name" class="form-select" required><option value="">Select Class</option>@foreach($classes as $class)<option value="{{ $class->name }}">{{ $class->name }}</option>@endforeach</select></div><div class="col-md-2"><label class="form-label">Section</label><input name="section" class="form-control" placeholder="Optional e.g. A"></div><div class="col-md-2"><label class="form-label">Status</label><select name="status" class="form-select"><option value="all">All Students</option><option value="active">Active Only</option><option value="inactive">Inactive Only</option></select></div><div class="col-md-2 d-flex align-items-end"><button class="btn btn-success w-100">View Report</button></div></div></form><div class="form-text mt-2">Choose a campus to keep same-named classes from different campuses separated in reports.</div></div></div>
<div class="card border-0 shadow-sm"><div class="card-body p-4"><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Photo</th><th>Student</th><th>Admission No.</th><th>Campus</th><th>Class</th><th>Roll</th><th>Status</th><th></th></tr></thead><tbody>@forelse($students as $student)<tr><td>@if($student->photo)<img src="{{ asset('storage/'.$student->photo) }}" alt="" width="48" height="58" class="rounded border" style="object-fit:cover">@else<div class="bg-light border rounded d-flex align-items-center justify-content-center text-secondary" style="width:48px;height:58px;font-size:10px">No Photo</div>@endif</td><td><div class="fw-semibold">{{ $student->user->name }}</div><small class="text-secondary">{{ $student->user->email }}</small></td><td>{{ $student->admission_no }}</td><td>{{ $student->branch?->name ?: '—' }}</td><td>{{ $student->class_name ?: '—' }} {{ $student->section ? '/ '.$student->section : '' }}</td><td>{{ $student->roll_no ?: '—' }}</td><td><span class="badge {{ $student->is_active ? 'bg-success' : 'bg-secondary' }}">{{ $student->is_active ? 'Active' : 'Inactive' }}</span></td><td class="text-end"><div class="d-flex flex-wrap justify-content-end gap-2"><a href="{{ route('admin.students.show',$student) }}" class="btn btn-sm btn-outline-secondary">View</a><a href="{{ route('admin.students.edit',$student) }}" class="btn btn-sm btn-outline-primary">Edit / Photo</a><form method="POST" action="{{ route('admin.students.status',$student) }}" onsubmit="return confirm('{{ $student->is_active ? 'Deactivate this student account?' : 'Activate this student account?' }}')">@csrf @method('PATCH')<button class="btn btn-sm {{ $student->is_active ? 'btn-outline-danger' : 'btn-outline-success' }}" type="submit">{{ $student->is_active ? 'Deactivate' : 'Activate' }}</button></form></div></td></tr>@empty<tr><td colspan="8" class="text-center text-secondary py-4">No students found.</td></tr>@endforelse</tbody></table></div></div></div>
@endsection
