@extends('admin.layouts.app')
@section('title','Student Details')
@section('heading','Student Details')
@section('content')
@if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
<div class="d-flex flex-wrap justify-content-between align-items-center gap-3 mb-4"><div><h1 class="fw-bold mb-1">Student Profile</h1><p class="text-secondary mb-0">Complete student and guardian information.</p></div><div class="d-flex flex-wrap gap-2"><form method="POST" action="{{ route('admin.students.status',$student) }}" onsubmit="return confirm('{{ $student->is_active ? 'Deactivate this student account?' : 'Activate this student account?' }}')">@csrf @method('PATCH')<button type="submit" class="btn {{ $student->is_active ? 'btn-outline-danger' : 'btn-success' }}"><i class="fa-solid {{ $student->is_active ? 'fa-user-slash' : 'fa-user-check' }} me-1"></i>{{ $student->is_active ? 'Deactivate' : 'Activate' }}</button></form><a href="{{ route('admin.students.edit',$student) }}" class="btn btn-primary"><i class="fa-solid fa-pen me-1"></i> Edit Student</a><a href="{{ route('admin.students.index') }}" class="btn btn-outline-secondary">Back</a></div></div>
<div class="row g-4"><div class="col-lg-4"><div class="card border-0 shadow-sm h-100"><div class="card-body p-4 text-center">@if($student->photo)<img src="{{ asset('storage/'.$student->photo) }}" alt="{{ $student->user->name }}" class="rounded-4 border mb-3" style="width:150px;height:180px;object-fit:cover">@else<div class="mx-auto bg-light border rounded-4 d-flex align-items-center justify-content-center text-secondary mb-3" style="width:150px;height:180px">No Photo</div>@endif<h3 class="fw-bold mb-1">{{ $student->user->name }}</h3><div class="text-secondary mb-3">{{ $student->admission_no }}</div><span class="badge rounded-pill {{ $student->is_active ? 'bg-success' : 'bg-secondary' }} px-3 py-2">{{ $student->is_active ? 'Active Student' : 'Inactive Student' }}</span></div></div></div>
<div class="col-lg-8"><div class="card border-0 shadow-sm"><div class="card-body p-4"><h5 class="fw-bold mb-3">Academic & Login Details</h5><div class="row g-3"><div class="col-md-6"><small class="text-secondary d-block">Login Email</small><strong>{{ $student->user->email }}</strong></div><div class="col-md-6"><small class="text-secondary d-block">Admission No.</small><strong>{{ $student->admission_no }}</strong></div><div class="col-md-4"><small class="text-secondary d-block">Class</small><strong>{{ $student->class_name ?: '—' }}</strong></div><div class="col-md-4"><small class="text-secondary d-block">Section</small><strong>{{ $student->section ?: '—' }}</strong></div><div class="col-md-4"><small class="text-secondary d-block">Roll No.</small><strong>{{ $student->roll_no ?: '—' }}</strong></div><div class="col-md-6"><small class="text-secondary d-block">Date of Birth</small><strong>{{ $student->date_of_birth ? $student->date_of_birth->format('d M Y') : '—' }}</strong></div><div class="col-md-6"><small class="text-secondary d-block">Gender</small><strong>{{ $student->gender ?: '—' }}</strong></div></div><hr class="my-4"><h5 class="fw-bold mb-3">Guardian Details</h5><div class="row g-3"><div class="col-md-6"><small class="text-secondary d-block">Guardian Name</small><strong>{{ $student->guardian_name ?: '—' }}</strong></div><div class="col-md-6"><small class="text-secondary d-block">Guardian Phone</small><strong>{{ $student->guardian_phone ?: '—' }}</strong></div><div class="col-12"><small class="text-secondary d-block">Address</small><strong>{{ $student->address ?: '—' }}</strong></div></div></div></div></div></div>
@endsection
