<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Gallery | Senet Pathshala Admin</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"></head>
<body class="bg-light">
<nav class="navbar navbar-dark bg-dark"><div class="container"><a class="navbar-brand fw-bold" href="{{ route('admin.dashboard') }}">Senet Pathshala Admin</a></div></nav>
<div class="container py-5"><div class="d-flex justify-content-between align-items-center mb-4"><div><h1>Gallery</h1><p class="text-secondary mb-0">Upload and manage school photographs.</p></div><a href="{{ route('admin.dashboard') }}" class="btn btn-outline-secondary">Dashboard</a></div>
@if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
<div class="card border-0 shadow-sm mb-4"><div class="card-body"><h5>Upload Image</h5><form action="{{ route('admin.gallery.store') }}" method="POST" enctype="multipart/form-data" class="row g-3">@csrf<div class="col-md-6"><label class="form-label">Title</label><input name="title" class="form-control" required></div><div class="col-md-6"><label class="form-label">Image</label><input type="file" name="image" class="form-control" accept="image/*" required></div><div class="col-12"><button class="btn btn-primary">Upload</button></div></form></div></div>
<div class="row g-4">@forelse($galleries as $gallery)<div class="col-md-4 col-lg-3"><div class="card border-0 shadow-sm h-100"><img src="{{ asset('storage/'.$gallery->image) }}" class="card-img-top" style="height:180px;object-fit:cover" alt="{{ $gallery->title }}"><div class="card-body"><h6>{{ $gallery->title }}</h6><form action="{{ route('admin.gallery.destroy', $gallery) }}" method="POST" onsubmit="return confirm('Delete this image?')">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger">Delete</button></form></div></div></div>@empty<div class="col-12"><div class="alert alert-secondary">No gallery images uploaded yet.</div></div>@endforelse</div><div class="mt-4">{{ $galleries->links() }}</div>
</div></body></html>
