<?php
namespace App\Http\Controllers\Student;
use App\Http\Controllers\Controller;
use App\Models\Attendance;
use App\Models\Branch;
use App\Models\Homework;
use App\Models\ExamResult;
use App\Models\FeePayment;
use App\Models\SchoolSetting;
use App\Models\StudentDocument;
use Illuminate\Http\Request;
use Illuminate\View\View;
class DashboardController extends Controller {
public function index(Request $request): View {$student=$this->studentFor($request);$student->load(['user','branch']);$attendance=Attendance::where('student_id',$student->id)->get();$present=$attendance->where('status','Present')->count();$absent=$attendance->where('status','Absent')->count();$attendanceDays=$present+$absent;$attendancePercentage=$attendanceDays>0?round(($present/$attendanceDays)*100,1):0;$payments=FeePayment::where('student_id',$student->id)->get();$totalFee=$payments->isNotEmpty()?(float)$payments->sortByDesc('id')->first()->total_fee:0;$totalPaid=(float)$payments->sum(fn($p)=>(float)$p->amount_paid);$pendingFee=max(0,$totalFee-$totalPaid);$latestExam=ExamResult::where('student_id',$student->id)->latest('id')->value('exam_name');$resultPercentage=null;if($latestExam){$rows=ExamResult::where('student_id',$student->id)->where('exam_name',$latestExam)->get();$max=(float)$rows->sum(fn($r)=>(float)$r->max_marks);$obt=(float)$rows->sum(fn($r)=>(float)$r->marks_obtained);$resultPercentage=$max>0?round(($obt/$max)*100,1):0;}$homeworkCount=Homework::where('class_name',$student->class_name)->where(function($q)use($student){$q->whereNull('branch_id')->orWhere('branch_id',$student->branch_id);})->where(function($q)use($student){$q->whereNull('section')->orWhere('section','')->orWhere('section',$student->section);})->count();$documentCount=StudentDocument::where('student_id',$student->id)->count();return view('student.dashboard',compact('student','attendancePercentage','pendingFee','latestExam','resultPercentage','homeworkCount','documentCount'));}
public function profile(Request $request): View {$student=$this->studentFor($request);$student->load(['user','branch']);return view('student.profile',compact('student'));}
public function idCard(Request $request): View {$student=$this->studentFor($request);$student->load(['user','branch']);return view('student.id-card',compact('student'));}
public function attendance(Request $request): View {$student=$this->studentFor($request);$records=Attendance::where('student_id',$student->id)->latest('attendance_date')->get();$present=$records->where('status','Present')->count();$absent=$records->where('status','Absent')->count();$leave=$records->where('status','Leave')->count();$workingDays=$present+$absent;$percentage=$workingDays>0?round(($present/$workingDays)*100,1):0;return view('student.attendance',compact('student','records','present','absent','leave','percentage'));}
public function homework(Request $request): View {$student=$this->studentFor($request);$homeworks=Homework::with('branch')->where('class_name',$student->class_name)->where(function($q)use($student){$q->whereNull('branch_id')->orWhere('branch_id',$student->branch_id);})->where(function($q)use($student){$q->whereNull('section')->orWhere('section','')->orWhere('section',$student->section);})->latest('homework_date')->latest('id')->get();return view('student.homework',compact('student','homeworks'));}
public function results(Request $request): View {$student=$this->studentFor($request);$results=ExamResult::where('student_id',$student->id)->orderBy('exam_name')->orderBy('subject')->get();$exams=$results->groupBy('exam_name');return view('student.results',compact('student','exams'));}
public function reportCard(Request $request,string $exam): View {$student=$this->studentFor($request);$student->load(['user','branch']);$results=ExamResult::where('student_id',$student->id)->where('exam_name',$exam)->orderBy('subject')->get();abort_if($results->isEmpty(),404);$total=(float)$results->sum(fn($r)=>(float)$r->max_marks);$obtained=(float)$results->sum(fn($r)=>(float)$r->marks_obtained);$percentage=$total>0?round(($obtained/$total)*100,1):0;$grade=$percentage>=90?'A+':($percentage>=80?'A':($percentage>=70?'B+':($percentage>=60?'B':($percentage>=50?'C':($percentage>=40?'D':'F')))));$result=$percentage>=40?'PASS':'FAIL';$school=SchoolSetting::first();return view('student.report-card',compact('student','results','exam','total','obtained','percentage','grade','result','school'));}
public function fees(Request $request): View {$student=$this->studentFor($request);$payments=FeePayment::where('student_id',$student->id)->latest('payment_date')->latest('id')->get();$totalFee=$payments->isNotEmpty()?(float)$payments->first()->total_fee:0;$totalPaid=(float)$payments->sum(fn($p)=>(float)$p->amount_paid);$pending=max(0,$totalFee-$totalPaid);return view('student.fees',compact('student','payments','totalFee','totalPaid','pending'));}
public function feeReceipt(Request $request,FeePayment $payment): View {$student=$this->studentFor($request);abort_unless((int)$payment->student_id===(int)$student->id,403);$payment->load(['student.user','student.branch']);$settings=SchoolSetting::first();$paidTillNow=(float)FeePayment::where('student_id',$student->id)->where(function($q)use($payment){$q->where('payment_date','<',$payment->payment_date)->orWhere(function($q)use($payment){$q->where('payment_date',$payment->payment_date)->where('id','<=',$payment->id);});})->sum('amount_paid');$pending=max(0,(float)$payment->total_fee-$paidTillNow);return view('student.fee-receipt',compact('payment','settings','paidTillNow','pending'));}
public function documents(Request $request): View {$student=$this->studentFor($request);$documents=StudentDocument::where('student_id',$student->id)->latest('id')->get();return view('student.documents',compact('student','documents'));}
private function studentFor(Request $request){$user=$request->user();$student=$user->student;abort_unless($student&&$student->is_active,403,'Student account is inactive.');abort_unless($student->branch_id&&Branch::whereKey($student->branch_id)->where('is_active',true)->exists(),403,'No active campus is assigned to this student account.');abort_unless((int)$user->branch_id===(int)$student->branch_id,403,'Student account campus assignment is inconsistent.');return $student;}
}
