@extends('admin.layouts.app')
@section('title','Fees Management')
@section('heading','Fees Management')
@section('content')
<div class="mb-4"><h1 class="fw-bold mb-1">Fees Management</h1><p class="text-secondary mb-0">Record student payments and track pending balances.</p></div>
@if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
@if($errors->any())<div class="alert alert-danger"><ul class="mb-0">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<div class="card border-0 shadow-sm mb-4"><div class="card-body"><form method="GET" action="{{ route('admin.fees.index') }}" class="row g-2"><div class="col-md-9"><label class="form-label">Search Student</label><input type="search" name="q" value="{{ $search }}" class="form-control" placeholder="Admission number or student name"></div><div class="col-md-3 d-flex align-items-end gap-2"><button class="btn btn-primary flex-fill">Search</button>@if($search !== '')<a href="{{ route('admin.fees.index') }}" class="btn btn-outline-secondary">Clear</a>@endif</div></form></div></div>
<div class="card border-0 shadow-sm mb-4"><div class="card-body p-4"><h5 class="fw-bold mb-3">Add Payment</h5><form method="POST" action="{{ route('admin.fees.store') }}">@csrf<div class="row g-3"><div class="col-lg-4"><label class="form-label">Student *</label><select name="student_id" class="form-select" required><option value="">Select Student</option>@foreach($students as $student)<option value="{{ $student->id }}" @selected(old('student_id')==$student->id)>{{ $student->admission_no }} — {{ $student->user->name }}</option>@endforeach</select></div><div class="col-lg-2 col-md-4"><label class="form-label">Total Fee ₹ *</label><input type="number" step="0.01" min="0" name="total_fee" value="{{ old('total_fee') }}" class="form-control" required></div><div class="col-lg-2 col-md-4"><label class="form-label">Pay Now ₹ *</label><input type="number" step="0.01" min="0.01" name="amount_paid" value="{{ old('amount_paid') }}" class="form-control" required></div><div class="col-lg-2 col-md-4"><label class="form-label">Payment Date *</label><input type="date" name="payment_date" value="{{ old('payment_date',now()->format('Y-m-d')) }}" class="form-control" required></div><div class="col-lg-2"><label class="form-label">Mode *</label><select name="payment_mode" class="form-select" required>@foreach(['Cash','UPI','Bank Transfer','Cheque'] as $mode)<option @selected(old('payment_mode','Cash')===$mode)>{{ $mode }}</option>@endforeach</select></div><div class="col-lg-10"><label class="form-label">Note</label><input name="note" value="{{ old('note') }}" class="form-control" placeholder="Optional note"></div><div class="col-lg-2 d-flex align-items-end"><button class="btn btn-primary w-100" type="submit"><i class="fa-solid fa-indian-rupee-sign me-1"></i> Save Payment</button></div></div></form></div></div>
<div class="card border-0 shadow-sm mb-4"><div class="card-body p-4"><h5 class="fw-bold mb-3">Student Fee Summary</h5><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Student</th><th>Admission</th><th>Total Fee</th><th>Paid</th><th>Pending</th></tr></thead><tbody>@forelse($students as $student)@php($s=$summaries->get($student->id))<tr><td class="fw-semibold">{{ $student->user->name }}</td><td>{{ $student->admission_no }}</td><td>₹{{ number_format($s['total'] ?? 0,2) }}</td><td class="text-success fw-semibold">₹{{ number_format($s['paid'] ?? 0,2) }}</td><td class="{{ ($s['pending'] ?? 0)>0 ? 'text-danger' : 'text-success' }} fw-bold">₹{{ number_format($s['pending'] ?? 0,2) }}</td></tr>@empty<tr><td colspan="5" class="text-center text-secondary">No students found.</td></tr>@endforelse</tbody></table></div></div></div>
<div class="card border-0 shadow-sm"><div class="card-body p-4"><h5 class="fw-bold mb-3">Payment History</h5><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Receipt</th><th>Date</th><th>Student</th><th>Amount</th><th>Mode</th><th>Note</th><th></th></tr></thead><tbody>@forelse($payments as $payment)<tr><td><span class="badge bg-light text-dark border">{{ $payment->receipt_no }}</span></td><td>{{ $payment->payment_date->format('d M Y') }}</td><td><strong>{{ $payment->student->user->name }}</strong><br><small class="text-secondary">{{ $payment->student->admission_no }}</small></td><td class="fw-bold text-success">₹{{ number_format($payment->amount_paid,2) }}</td><td>{{ $payment->payment_mode }}</td><td>{{ $payment->note ?: '—' }}</td><td class="text-end"><a href="{{ route('admin.fees.receipt',$payment) }}" class="btn btn-sm btn-outline-primary" target="_blank"><i class="fa-solid fa-print me-1"></i>Print</a></td></tr>@empty<tr><td colspan="7" class="text-center text-secondary py-4">No fee payments recorded yet.</td></tr>@endforelse</tbody></table></div></div></div>
@endsection
