<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0">
<title>Fee Receipt - {{ $payment->receipt_no }}</title>
<style>
*{box-sizing:border-box}body{margin:0;background:#eef2f7;font-family:Arial,sans-serif;color:#172033}.toolbar{max-width:820px;margin:20px auto 10px;display:flex;justify-content:flex-end;gap:10px}.toolbar a,.toolbar button{border:0;border-radius:8px;padding:10px 18px;font-weight:700;cursor:pointer;text-decoration:none}.back{background:#fff;color:#333;border:1px solid #ccd3dc!important}.print{background:#1677ff;color:#fff}.receipt{width:800px;max-width:calc(100% - 30px);margin:0 auto 30px;background:#fff;border:1px solid #cfd7e3;padding:28px 34px;box-shadow:0 8px 30px rgba(0,0,0,.08)}.header{display:flex;align-items:center;gap:18px;border-bottom:3px solid #1677ff;padding-bottom:16px}.logo{width:76px;height:76px;object-fit:contain}.school{flex:1;text-align:center}.school h1{margin:0 0 5px;font-size:27px;color:#0d5fc7}.school p{margin:3px 0;font-size:13px;color:#555}.title{text-align:center;margin:20px 0 16px}.title span{display:inline-block;background:#1677ff;color:#fff;padding:8px 28px;border-radius:20px;font-weight:700;letter-spacing:.5px}.grid{display:grid;grid-template-columns:1fr 1fr;border:1px solid #dce2ea;border-radius:8px;overflow:hidden}.item{padding:11px 14px;border-bottom:1px solid #e5e9ef}.item:nth-child(odd){border-right:1px solid #e5e9ef}.label{font-size:11px;text-transform:uppercase;color:#788493;margin-bottom:4px}.value{font-weight:700}.amount{margin-top:18px;width:100%;border-collapse:collapse}.amount th,.amount td{padding:11px;border:1px solid #dce2ea;text-align:right}.amount th:first-child,.amount td:first-child{text-align:left}.paid{color:#11863b}.pending{color:#c62828}.words{margin-top:15px;padding:12px;background:#f6f9fd;border-radius:7px}.footer{display:flex;justify-content:space-between;align-items:flex-end;margin-top:38px}.note{max-width:55%;font-size:13px;color:#555}.sign{text-align:center;min-width:170px}.line{border-top:1px solid #333;margin-bottom:6px}.thanks{text-align:center;margin-top:28px;color:#697586;font-size:12px}
@media print{@page{size:A4 portrait;margin:12mm}body{background:#fff}.toolbar{display:none}.receipt{width:100%;max-width:none;margin:0;border:1px solid #999;box-shadow:none;padding:22px 28px}.header{break-inside:avoid}.title,.grid,.amount,.footer{break-inside:avoid}}
</style>
</head>
<body>
<div class="toolbar"><a class="back" href="{{ route('admin.fees.index') }}">← Back</a><button class="print" onclick="window.print()">Print Receipt</button></div>
<div class="receipt">
<div class="header">@if($settings?->logo)<img class="logo" src="{{ asset('storage/'.$settings->logo) }}" alt="Logo">@else<img class="logo" src="{{ asset('images/logo.png') }}" alt="Logo">@endif<div class="school"><h1>{{ $settings?->school_name ?? 'C-Net Pathshala' }}</h1>@if($settings?->address)<p>{{ $settings->address }}</p>@endif<p>@if($settings?->phone)Phone: {{ $settings->phone }}@endif @if($settings?->email) &nbsp; | &nbsp; {{ $settings->email }}@endif</p></div></div>
<div class="title"><span>FEE RECEIPT</span></div>
<div class="grid"><div class="item"><div class="label">Receipt No.</div><div class="value">{{ $payment->receipt_no }}</div></div><div class="item"><div class="label">Payment Date</div><div class="value">{{ $payment->payment_date->format('d M Y') }}</div></div><div class="item"><div class="label">Student Name</div><div class="value">{{ $payment->student->user->name }}</div></div><div class="item"><div class="label">Admission No.</div><div class="value">{{ $payment->student->admission_no }}</div></div><div class="item"><div class="label">Class / Section</div><div class="value">{{ $payment->student->class_name ?: '—' }}{{ $payment->student->section ? ' / '.$payment->student->section : '' }}</div></div><div class="item"><div class="label">Payment Mode</div><div class="value">{{ $payment->payment_mode }}</div></div></div>
<table class="amount"><tr><th>Description</th><th>Amount</th></tr><tr><td>Total Fee</td><td>₹{{ number_format($payment->total_fee,2) }}</td></tr><tr><td>Amount Received (this receipt)</td><td class="paid"><strong>₹{{ number_format($payment->amount_paid,2) }}</strong></td></tr><tr><td>Paid Till Date</td><td>₹{{ number_format($paidTillNow,2) }}</td></tr><tr><td><strong>Balance Pending</strong></td><td class="pending"><strong>₹{{ number_format($pending,2) }}</strong></td></tr></table>
@if($payment->note)<div class="words"><strong>Note:</strong> {{ $payment->note }}</div>@endif
<div class="footer"><div class="note">This is a computer-generated fee receipt. Please keep it safely for school records.</div><div class="sign"><div class="line"></div><strong>Authorized Signature</strong></div></div><div class="thanks">Thank you for your payment.</div>
</div>
</body></html>
