@extends('admin.layouts.app')
@section('title','Homework')
@section('heading','Homework')
@section('content')
<div class="mb-4"><h1 class="fw-bold mb-1">Homework / Assignments</h1><p class="text-secondary mb-0">Publish class-wise homework for students.</p></div>
@if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
@if($errors->any())<div class="alert alert-danger"><ul class="mb-0">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<div class="card border-0 shadow-sm mb-4"><div class="card-body p-4"><h5 class="fw-bold mb-3">Add Homework</h5><form method="POST" action="{{ route('admin.homework.store') }}">@csrf<div class="row g-3"><div class="col-md-3"><label class="form-label">Class *</label><input name="class_name" list="class-list" value="{{ old('class_name') }}" class="form-control" required><datalist id="class-list">@foreach($classes as $class)<option value="{{ $class }}">@endforeach</datalist></div><div class="col-md-2"><label class="form-label">Section</label><input name="section" value="{{ old('section') }}" class="form-control" placeholder="A"></div><div class="col-md-3"><label class="form-label">Subject *</label><input name="subject" value="{{ old('subject') }}" class="form-control" required placeholder="Mathematics"></div><div class="col-md-2"><label class="form-label">Homework Date *</label><input type="date" name="homework_date" value="{{ old('homework_date',now()->format('Y-m-d')) }}" class="form-control" required></div><div class="col-md-2"><label class="form-label">Due Date</label><input type="date" name="due_date" value="{{ old('due_date') }}" class="form-control"></div><div class="col-12"><label class="form-label">Homework Details *</label><textarea name="details" rows="3" class="form-control" required placeholder="Write assignment details here...">{{ old('details') }}</textarea></div><div class="col-12 text-end"><button class="btn btn-primary px-4"><i class="fa-solid fa-paper-plane me-1"></i> Publish Homework</button></div></div></form></div></div>
<div class="card border-0 shadow-sm"><div class="card-body p-4"><h5 class="fw-bold mb-3">Published Homework</h5><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Date</th><th>Class</th><th>Subject</th><th>Homework</th><th>Due</th><th></th></tr></thead><tbody>@forelse($homeworks as $homework)<tr><td>{{ $homework->homework_date->format('d M Y') }}</td><td><strong>{{ $homework->class_name }}</strong>{{ $homework->section ? ' / '.$homework->section : '' }}</td><td>{{ $homework->subject }}</td><td style="min-width:260px">{{ $homework->details }}</td><td>{{ $homework->due_date?->format('d M Y') ?? '—' }}</td><td class="text-end"><form method="POST" action="{{ route('admin.homework.destroy',$homework) }}" onsubmit="return confirm('Delete this homework?')">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger">Delete</button></form></td></tr>@empty<tr><td colspan="6" class="text-center text-secondary py-4">No homework published yet.</td></tr>@endforelse</tbody></table></div></div></div>
@endsection
