@extends('admin.layouts.app')
@section('title','Homework')
@section('heading','Homework')
@section('content')
<div class="mb-4"><h1 class="fw-bold mb-1">Homework / Assignments</h1><p class="text-secondary mb-0">Publish campus and class-wise homework for students.</p></div>
@if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
@if($errors->any())<div class="alert alert-danger"><ul class="mb-0">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<div class="card border-0 shadow-sm mb-4"><div class="card-body"><form method="GET" action="{{ route('admin.homework.index') }}" class="row g-2"><div class="col-md-4"><label class="form-label">Campus</label><select name="branch_id" class="form-select"><option value="">All Campuses</option>@foreach($branches as $branch)<option value="{{ $branch->id }}" @selected((string)request('branch_id')===(string)$branch->id)>{{ $branch->name }}</option>@endforeach</select></div><div class="col-md-2 d-flex align-items-end"><button class="btn btn-primary w-100">Filter</button></div></form></div></div>
<div class="card border-0 shadow-sm mb-4"><div class="card-body p-4"><h5 class="fw-bold mb-3">Add Homework</h5><form method="POST" action="{{ route('admin.homework.store') }}">@csrf<div class="row g-3"><div class="col-md-3"><label class="form-label">Campus *</label><select name="branch_id" id="homeworkBranch" class="form-select" required><option value="">Select Campus</option>@foreach($branches as $branch)<option value="{{ $branch->id }}" @selected((string)old('branch_id',request('branch_id'))===(string)$branch->id)>{{ $branch->name }}</option>@endforeach</select></div><div class="col-md-3"><label class="form-label">Class *</label><select name="class_name" id="homeworkClass" class="form-select" required><option value="">Select Class</option>@foreach($classes as $class)<option value="{{ $class->name }}" data-branch="{{ $class->branch_id }}" data-sections='@json($class->section_list)' @selected(old('class_name')===$class->name)>{{ $class->name }}</option>@endforeach</select></div><div class="col-md-2"><label class="form-label">Section</label><select name="section" id="homeworkSection" class="form-select"><option value="">Select Section</option></select></div><div class="col-md-2"><label class="form-label">Subject *</label><input name="subject" value="{{ old('subject') }}" class="form-control" required placeholder="Mathematics"></div><div class="col-md-2"><label class="form-label">Homework Date *</label><input type="date" name="homework_date" value="{{ old('homework_date',now()->format('Y-m-d')) }}" class="form-control" required></div><div class="col-md-3"><label class="form-label">Due Date</label><input type="date" name="due_date" value="{{ old('due_date') }}" class="form-control"></div><div class="col-md-9"><label class="form-label">Homework Details *</label><textarea name="details" rows="3" class="form-control" required placeholder="Write assignment details here...">{{ old('details') }}</textarea></div><div class="col-12 text-end"><button class="btn btn-primary px-4"><i class="fa-solid fa-paper-plane me-1"></i> Publish Homework</button></div></div></form></div></div>
<div class="card border-0 shadow-sm"><div class="card-body p-4"><h5 class="fw-bold mb-3">Published Homework</h5><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Date</th><th>Campus</th><th>Class</th><th>Subject</th><th>Homework</th><th>Due</th><th></th></tr></thead><tbody>@forelse($homeworks as $homework)<tr><td>{{ $homework->homework_date->format('d M Y') }}</td><td>{{ $homework->branch?->name ?: 'Legacy / Unassigned' }}</td><td><strong>{{ $homework->class_name }}</strong>{{ $homework->section ? ' / '.$homework->section : '' }}</td><td>{{ $homework->subject }}</td><td style="min-width:260px">{{ $homework->details }}</td><td>{{ $homework->due_date?->format('d M Y') ?? '—' }}</td><td class="text-end"><form method="POST" action="{{ route('admin.homework.destroy',$homework) }}" onsubmit="return confirm('Delete this homework?')">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger">Delete</button></form></td></tr>@empty<tr><td colspan="7" class="text-center text-secondary py-4">No homework published yet.</td></tr>@endforelse</tbody></table></div></div></div>
<script>document.addEventListener('DOMContentLoaded',function(){const b=document.getElementById('homeworkBranch'),c=document.getElementById('homeworkClass'),s=document.getElementById('homeworkSection'),oldClass=@json(old('class_name')),oldSection=@json(old('section'));const all=[...c.options].slice(1).map(o=>({value:o.value,text:o.textContent,branch:o.dataset.branch||'',sections:o.dataset.sections||'[]'}));function classes(){const v=b.value,keep=c.value||oldClass;c.innerHTML='<option value="">Select Class</option>';all.filter(x=>!x.branch||x.branch===v).forEach(x=>{const o=document.createElement('option');o.value=x.value;o.textContent=x.text;o.dataset.branch=x.branch;o.dataset.sections=x.sections;if(x.value===keep)o.selected=true;c.appendChild(o)});sections()}function sections(){const o=c.options[c.selectedIndex];let list=[];try{list=JSON.parse(o?.dataset?.sections||'[]')}catch(e){}const keep=s.value||oldSection;s.innerHTML='<option value="">Select Section</option>';list.forEach(v=>{const x=document.createElement('option');x.value=v;x.textContent=v;if(v===keep)x.selected=true;s.appendChild(x)})}b.addEventListener('change',classes);c.addEventListener('change',sections);classes()});</script>
@endsection
