@extends('admin.layouts.app')
@section('title','Certificates & Documents')
@section('heading','Certificates & Documents')
@section('content')
<div class="mb-4"><h1 class="fw-bold mb-1">Certificates & Documents</h1><p class="text-secondary mb-0">Generate school certificates automatically or upload external documents.</p></div>
@if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
@if($errors->any())<div class="alert alert-danger"><ul class="mb-0">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<div class="card border-0 shadow-sm mb-4"><div class="card-body p-4"><div class="d-flex align-items-center gap-3 mb-3"><div class="rounded-circle bg-success-subtle text-success d-flex align-items-center justify-content-center" style="width:48px;height:48px"><i class="fa-solid fa-certificate fs-4"></i></div><div><h5 class="fw-bold mb-0">Automatic Certificate Generator</h5><small class="text-secondary">Student details will be filled automatically.</small></div></div><form method="POST" action="{{ route('admin.documents.generate') }}" target="_blank">@csrf<div class="row g-3"><div class="col-lg-4"><label class="form-label">Student *</label><select name="student_id" class="form-select" required><option value="">Select Student</option>@foreach($students as $student)<option value="{{ $student->id }}">{{ $student->admission_no }} — {{ $student->user->name }} ({{ $student->class_name }})</option>@endforeach</select></div><div class="col-lg-3"><label class="form-label">Certificate Type *</label><select name="certificate_type" class="form-select" required><option value="bonafide">Bonafide Certificate</option><option value="character">Character Certificate</option><option value="study">Study Certificate</option></select></div><div class="col-lg-3"><label class="form-label">Purpose</label><input name="purpose" class="form-control" placeholder="e.g. Bank / Scholarship"></div><div class="col-lg-2 d-flex align-items-end"><button class="btn btn-success w-100"><i class="fa-solid fa-wand-magic-sparkles me-1"></i> Generate</button></div></div></form></div></div>
<div class="card border-0 shadow-sm mb-4"><div class="card-body p-4"><h5 class="fw-bold mb-3">Upload External Document</h5><form method="POST" action="{{ route('admin.documents.store') }}" enctype="multipart/form-data">@csrf<div class="row g-3"><div class="col-lg-4"><label class="form-label">Student *</label><select name="student_id" class="form-select" required><option value="">Select Student</option>@foreach($students as $student)<option value="{{ $student->id }}">{{ $student->admission_no }} — {{ $student->user->name }}</option>@endforeach</select></div><div class="col-lg-3"><label class="form-label">Title *</label><input name="title" class="form-control" required placeholder="Birth Certificate"></div><div class="col-lg-2"><label class="form-label">Type *</label><select name="document_type" class="form-select" required><option>Certificate</option><option>Marksheet</option><option>Identity Document</option><option>Other</option></select></div><div class="col-lg-3"><label class="form-label">File *</label><input type="file" name="document" class="form-control" accept=".pdf,.jpg,.jpeg,.png" required><small class="text-secondary">PDF/JPG/PNG, max 5 MB</small></div><div class="col-lg-10"><label class="form-label">Note</label><input name="note" class="form-control" placeholder="Optional note"></div><div class="col-lg-2 d-flex align-items-end"><button class="btn btn-primary w-100">Upload</button></div></div></form></div></div>
<div class="card border-0 shadow-sm"><div class="card-body p-4"><h5 class="fw-bold mb-3">Uploaded Documents</h5><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Student</th><th>Title</th><th>Type</th><th>File</th><th>Note</th><th></th></tr></thead><tbody>@forelse($documents as $document)<tr><td><strong>{{ $document->student->user->name }}</strong><br><small class="text-secondary">{{ $document->student->admission_no }}</small></td><td>{{ $document->title }}</td><td>{{ $document->document_type }}</td><td><a class="btn btn-sm btn-outline-primary" target="_blank" href="{{ asset('storage/'.$document->file_path) }}">View</a></td><td>{{ $document->note ?: '—' }}</td><td><form method="POST" action="{{ route('admin.documents.destroy',$document) }}" onsubmit="return confirm('Delete this document?')">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger">Delete</button></form></td></tr>@empty<tr><td colspan="6" class="text-center text-secondary py-4">No documents uploaded yet.</td></tr>@endforelse</tbody></table></div></div></div>
@endsection