@extends('admin.layouts.app')
@section('title','Campuses')
@section('heading','Campuses')
@section('content')
<div class="mb-4"><h1 class="fw-bold mb-1">Campuses</h1><p class="text-secondary mb-0">Manage Bihar Sharif, Goraur and future campus records from one place.</p></div>
@if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
@if($errors->any())<div class="alert alert-danger"><ul class="mb-0">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<div class="card border-0 shadow-sm mb-4"><div class="card-body p-4"><h5 class="fw-bold mb-3">Add Campus</h5><form method="POST" action="{{ route('admin.branches.store') }}">@csrf<div class="row g-3"><div class="col-md-4"><label class="form-label">Campus Name *</label><input name="name" value="{{ old('name') }}" class="form-control" required></div><div class="col-md-2"><label class="form-label">Code *</label><input name="code" value="{{ old('code') }}" class="form-control" placeholder="GORAUR" required></div><div class="col-md-3"><label class="form-label">Phone</label><input name="phone" value="{{ old('phone') }}" class="form-control"></div><div class="col-md-3"><label class="form-label">Email</label><input type="email" name="email" value="{{ old('email') }}" class="form-control"></div><div class="col-12"><label class="form-label">Address</label><input name="address" value="{{ old('address') }}" class="form-control"></div><div class="col-md-3"><input type="hidden" name="is_main" value="0"><div class="form-check mt-2"><input class="form-check-input" type="checkbox" name="is_main" value="1" id="newMain"><label class="form-check-label" for="newMain">Main Campus</label></div></div><div class="col-md-3"><input type="hidden" name="is_active" value="0"><div class="form-check mt-2"><input class="form-check-input" type="checkbox" name="is_active" value="1" id="newActive" checked><label class="form-check-label" for="newActive">Active</label></div></div><div class="col-md-6 text-md-end"><button class="btn btn-primary px-4">Add Campus</button></div></div></form></div></div>
<div class="card border-0 shadow-sm"><div class="card-body p-4"><h5 class="fw-bold mb-3">Existing Campuses</h5><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Campus</th><th>Code</th><th>Students</th><th>Applications</th><th>Status</th><th class="text-end">Action</th></tr></thead><tbody>@forelse($branches as $branch)<tr><td><strong>{{ $branch->name }}</strong>@if($branch->is_main)<span class="badge bg-primary ms-2">Main</span>@endif<div class="small text-secondary">{{ $branch->address ?: 'No address added' }}</div></td><td>{{ $branch->code }}</td><td>{{ $branch->students_count }}</td><td>{{ $branch->admission_applications_count }}</td><td><span class="badge {{ $branch->is_active?'bg-success':'bg-secondary' }}">{{ $branch->is_active?'Active':'Inactive' }}</span></td><td class="text-end"><button class="btn btn-sm btn-outline-primary" data-bs-toggle="modal" data-bs-target="#editBranch{{ $branch->id }}">Edit</button></td></tr>@empty<tr><td colspan="6" class="text-center text-secondary py-4">No campuses found.</td></tr>@endforelse</tbody></table></div></div></div>
@foreach($branches as $branch)<div class="modal fade" id="editBranch{{ $branch->id }}" tabindex="-1" aria-hidden="true"><div class="modal-dialog modal-lg"><div class="modal-content"><div class="modal-header"><h5 class="modal-title">Edit {{ $branch->name }}</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><form method="POST" action="{{ route('admin.branches.update',$branch) }}">@csrf @method('PUT')<div class="modal-body"><div class="row g-3"><div class="col-md-6"><label class="form-label">Campus Name *</label><input name="name" value="{{ $branch->name }}" class="form-control" required></div><div class="col-md-3"><label class="form-label">Code *</label><input name="code" value="{{ $branch->code }}" class="form-control" required></div><div class="col-md-3"><label class="form-label">Phone</label><input name="phone" value="{{ $branch->phone }}" class="form-control"></div><div class="col-md-6"><label class="form-label">Email</label><input type="email" name="email" value="{{ $branch->email }}" class="form-control"></div><div class="col-md-6"><label class="form-label">Address</label><input name="address" value="{{ $branch->address }}" class="form-control"></div><div class="col-md-3"><input type="hidden" name="is_main" value="0"><div class="form-check"><input class="form-check-input" type="checkbox" name="is_main" value="1" id="main{{ $branch->id }}" @checked($branch->is_main)><label class="form-check-label" for="main{{ $branch->id }}">Main Campus</label></div></div><div class="col-md-3"><input type="hidden" name="is_active" value="0"><div class="form-check"><input class="form-check-input" type="checkbox" name="is_active" value="1" id="active{{ $branch->id }}" @checked($branch->is_active)><label class="form-check-label" for="active{{ $branch->id }}">Active</label></div></div></div></div><div class="modal-footer"><button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">Cancel</button><button class="btn btn-primary">Save Changes</button></div></form></div></div></div>@endforeach
@endsection
