@extends('admin.layouts.app')
@section('title','Classes & Sections')
@section('heading','Classes & Sections')
@section('content')
<div class="d-flex flex-wrap justify-content-between align-items-center gap-3 mb-4"><div><h1 class="fw-bold mb-1">Classes & Sections</h1><p class="text-secondary mb-0">Manage campus-wise class lists and available sections.</p></div><form method="GET" class="d-flex gap-2"><select name="branch_id" class="form-select"><option value="">All Campuses</option>@foreach($branches as $branch)<option value="{{ $branch->id }}" @selected((string)request('branch_id')===(string)$branch->id)>{{ $branch->name }}</option>@endforeach</select><button class="btn btn-outline-primary">Filter</button></form></div>
@if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
@if($errors->any())<div class="alert alert-danger"><ul class="mb-0">@foreach($errors->all() as $e)<li>{{ $e }}</li>@endforeach</ul></div>@endif
<div class="card border-0 shadow-sm mb-4"><div class="card-body p-4"><h5 class="fw-bold mb-3"><i class="fa-solid fa-plus-circle text-primary me-2"></i>Add Class</h5><form method="POST" action="{{ route('admin.classes.store') }}">@csrf<div class="row g-3"><div class="col-md-3"><label class="form-label">Campus</label><select name="branch_id" class="form-select"><option value="">All Campuses</option>@foreach($branches as $branch)<option value="{{ $branch->id }}" @selected((string)old('branch_id')===(string)$branch->id)>{{ $branch->name }}</option>@endforeach</select></div><div class="col-md-3"><label class="form-label">Class Name *</label><input name="name" value="{{ old('name') }}" class="form-control" placeholder="e.g. Nursery" required></div><div class="col-md-3"><label class="form-label">Sections</label><input name="sections" value="{{ old('sections') }}" class="form-control" placeholder="A, B, C"><div class="form-text">Separate multiple sections with commas.</div></div><div class="col-md-1"><label class="form-label">Order</label><input type="number" min="0" name="sort_order" value="{{ old('sort_order',0) }}" class="form-control"></div><div class="col-md-2 d-flex align-items-end"><div class="w-100"><div class="form-check mb-2"><input type="hidden" name="is_active" value="0"><input class="form-check-input" type="checkbox" name="is_active" value="1" id="newActive" checked><label class="form-check-label" for="newActive">Active</label></div><button class="btn btn-primary w-100">Add Class</button></div></div></div></form></div></div>
<div class="card border-0 shadow-sm"><div class="card-body p-4"><h5 class="fw-bold mb-3">Class List</h5><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Campus</th><th>Class</th><th>Sections</th><th>Order</th><th>Status</th><th style="width:330px">Actions</th></tr></thead><tbody>@forelse($classes as $class)<tr><form method="POST" action="{{ route('admin.classes.update',$class) }}">@csrf @method('PUT')<td><select name="branch_id" class="form-select"><option value="">All Campuses</option>@foreach($branches as $branch)<option value="{{ $branch->id }}" @selected((string)$class->branch_id===(string)$branch->id)>{{ $branch->name }}</option>@endforeach</select></td><td><input name="name" class="form-control" value="{{ $class->name }}" required></td><td><input name="sections" class="form-control" value="{{ $class->sections }}" placeholder="A, B, C"></td><td><input type="number" min="0" name="sort_order" class="form-control" value="{{ $class->sort_order }}"></td><td><input type="hidden" name="is_active" value="0"><div class="form-check form-switch"><input class="form-check-input" type="checkbox" name="is_active" value="1" @checked($class->is_active)></div></td><td><button class="btn btn-sm btn-success me-1">Save</button></form><form method="POST" action="{{ route('admin.classes.destroy',$class) }}" class="d-inline" onsubmit="return confirm('Delete this class? Existing students will not be deleted.')">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger">Delete</button></form></td></tr>@empty<tr><td colspan="6" class="text-center text-secondary py-4">No classes added yet.</td></tr>@endforelse</tbody></table></div></div></div>
@endsection
