@extends('admin.layouts.app')
@section('title', 'Enquiries')
@section('heading', 'Enquiries')
@section('content')
<div class="d-flex flex-wrap justify-content-between align-items-center gap-3 mb-4"><div><h1 class="fw-bold mb-1">Enquiries</h1><p class="text-secondary mb-0">Messages submitted through the website.</p></div><form method="GET" class="d-flex gap-2"><select name="branch_id" class="form-select"><option value="">All Campuses</option>@foreach($branches as $branch)<option value="{{ $branch->id }}" @selected((string)request('branch_id')===(string)$branch->id)>{{ $branch->name }}</option>@endforeach</select><button class="btn btn-outline-primary">Filter</button></form></div>
@if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
@if($errors->any())<div class="alert alert-danger"><ul class="mb-0">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<div class="card border-0 shadow-sm"><div class="card-body"><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Name</th><th>Campus</th><th>Mobile</th><th>Email</th><th>Message</th><th>Date</th><th style="min-width:300px">Reply</th></tr></thead><tbody>@forelse($contacts as $contact)<tr><td><strong>{{ $contact->name }}</strong></td><td>{{ $contact->branch?->name ?: '—' }}</td><td>{{ $contact->mobile }}</td><td>{{ $contact->email ?: '—' }}</td><td style="min-width:260px">{{ $contact->message ?: '—' }}</td><td>{{ $contact->created_at?->format('d M Y, h:i A') }}</td><td>@if($contact->email)<form action="{{ route('admin.contacts.reply',$contact) }}" method="POST" class="mb-2">@csrf<textarea name="reply_message" rows="3" class="form-control form-control-sm mb-2" placeholder="Type email reply..." required></textarea><button class="btn btn-sm btn-primary"><i class="fa-solid fa-reply me-1"></i>Send Reply</button></form>@else<small class="text-secondary d-block mb-2">No email address provided.</small>@endif<form action="{{ route('admin.contacts.destroy', $contact) }}" method="POST" onsubmit="return confirm('Delete this enquiry?')">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger">Delete</button></form></td></tr>@empty<tr><td colspan="7" class="text-center text-secondary py-5">No enquiries received yet.</td></tr>@endforelse</tbody></table></div>{{ $contacts->links() }}</div></div>
@endsection
