<?php
namespace App\Http\Controllers\Admin;
use App\Http\Controllers\Controller;use App\Models\Branch;use App\Models\FeePayment;use App\Models\SchoolSetting;use App\Models\Student;use Illuminate\Http\RedirectResponse;use Illuminate\Http\Request;use Illuminate\View\View;
class FeeController extends Controller
{
public function index(Request $request):View{abort_unless($request->user()->hasPermission('fees'),403);$user=$request->user();$search=trim((string)$request->query('q',''));$studentQuery=Student::with(['user','branch']);if(!$user->is_admin&&$user->branch_id)$studentQuery->where('branch_id',$user->branch_id);elseif($request->filled('branch_id'))$studentQuery->where('branch_id',$request->branch_id);if($user->isClassTeacher()){$studentQuery->where('class_name',$user->assigned_class);if($user->assigned_section)$studentQuery->where('section',$user->assigned_section);}if($search!==''){$studentQuery->where(function($q)use($search){$q->where('admission_no','like','%'.$search.'%')->orWhereHas('user',fn($userQuery)=>$userQuery->where('name','like','%'.$search.'%'));});}$students=$studentQuery->orderBy('admission_no')->get();$payments=FeePayment::with(['student.user','student.branch'])->whereIn('student_id',$students->pluck('id'))->latest('payment_date')->latest('id')->get();$summaries=$payments->groupBy('student_id')->map(function($rows){$total=(float)$rows->first()->total_fee;$paid=(float)$rows->sum('amount_paid');return ['total'=>$total,'paid'=>$paid,'pending'=>max(0,$total-$paid)];});$branches=$user->is_admin?Branch::where('is_active',true)->orderByDesc('is_main')->orderBy('name')->get():Branch::whereKey($user->branch_id)->get();return view('admin.fees.index',compact('students','payments','summaries','branches','search'));}
public function store(Request $request):RedirectResponse{abort_unless($request->user()->hasPermission('fees'),403);$data=$request->validate(['student_id'=>['required','exists:students,id'],'total_fee'=>['required','numeric','min:0'],'amount_paid'=>['required','numeric','gt:0'],'payment_date'=>['required','date'],'payment_mode'=>['required','in:Cash,UPI,Bank Transfer,Cheque'],'note'=>['nullable','string','max:255']]);$student=Student::findOrFail($data['student_id']);$this->guardStudentCampus($request,$student);$data['receipt_no']='CNET-FEE-'.now()->format('YmdHis').'-'.random_int(10,99);FeePayment::create($data);return back()->with('success','Fee payment recorded successfully. Receipt: '.$data['receipt_no']);}
public function receipt(Request $request,FeePayment $payment):View{abort_unless($request->user()->hasPermission('fees'),403);$payment->load(['student.user','student.branch']);$this->guardStudentCampus($request,$payment->student);$settings=SchoolSetting::first();$paidTillNow=(float)FeePayment::where('student_id',$payment->student_id)->where(function($q)use($payment){$q->where('payment_date','<',$payment->payment_date)->orWhere(function($q)use($payment){$q->where('payment_date',$payment->payment_date)->where('id','<=',$payment->id);});})->sum('amount_paid');$pending=max(0,(float)$payment->total_fee-$paidTillNow);return view('admin.fees.receipt',compact('payment','settings','paidTillNow','pending'));}
private function guardStudentCampus(Request $request,Student $student):void{$user=$request->user();if(!$user->is_admin&&$user->branch_id)abort_unless((int)$student->branch_id===(int)$user->branch_id,403);if($user->isClassTeacher())abort_unless($student->class_name===$user->assigned_class&&(!$user->assigned_section||$student->section===$user->assigned_section),403);}
}
