<?php
namespace App\Http\Controllers\Admin;
use App\Http\Controllers\Controller;use App\Models\ExamResult;use App\Models\SchoolSetting;use App\Models\Student;use Illuminate\Http\RedirectResponse;use Illuminate\Http\Request;use Illuminate\View\View;
class ResultController extends Controller
{
public function index(Request $request):View{abort_unless($request->user()->hasPermission('results')||$request->user()->hasPermission('report_cards'),403);$students=Student::with('user')->where('is_active',true)->orderBy('admission_no')->get();$results=ExamResult::with('student.user')->latest('exam_date')->latest('id')->get();$examNames=ExamResult::query()->select('exam_name')->distinct()->orderBy('exam_name')->pluck('exam_name');$classNames=Student::query()->whereNotNull('class_name')->where('class_name','!=','')->distinct()->orderBy('class_name')->pluck('class_name');$sectionNames=Student::query()->whereNotNull('section')->where('section','!=','')->distinct()->orderBy('section')->pluck('section');$canEditResults=$request->user()->hasPermission('results');return view('admin.results.index',compact('students','results','examNames','classNames','sectionNames','canEditResults'));}
public function store(Request $request):RedirectResponse{abort_unless($request->user()->hasPermission('results'),403);$data=$request->validate(['student_id'=>['required','exists:students,id'],'exam_name'=>['required','string','max:150'],'exam_date'=>['nullable','date'],'subjects'=>['required','array','min:1'],'subjects.*.subject'=>['required','string','max:150'],'subjects.*.max_marks'=>['required','numeric','min:0.01'],'subjects.*.marks_obtained'=>['required','numeric','min:0'],'subjects.*.remark'=>['nullable','string','max:255']]);foreach($data['subjects'] as $index=>$row){if((float)$row['marks_obtained']>(float)$row['max_marks'])return back()->withErrors(["subjects.$index.marks_obtained"=>'Marks obtained cannot be greater than maximum marks for '.$row['subject'].'.'])->withInput();ExamResult::updateOrCreate(['student_id'=>$data['student_id'],'exam_name'=>$data['exam_name'],'subject'=>$row['subject']],['max_marks'=>$row['max_marks'],'marks_obtained'=>$row['marks_obtained'],'exam_date'=>$data['exam_date']??null,'remark'=>$row['remark']??null]);}return back()->with('success',count($data['subjects']).' subject result(s) saved successfully.');}
public function edit(Request $request,ExamResult $result):View{abort_unless($request->user()->hasPermission('results'),403);$result->load('student.user');return view('admin.results.edit',compact('result'));}
public function update(Request $request,ExamResult $result):RedirectResponse{abort_unless($request->user()->hasPermission('results'),403);$data=$request->validate(['exam_name'=>['required','string','max:150'],'subject'=>['required','string','max:150'],'max_marks'=>['required','numeric','min:0.01'],'marks_obtained'=>['required','numeric','min:0'],'exam_date'=>['nullable','date'],'remark'=>['nullable','string','max:255']]);if((float)$data['marks_obtained']>(float)$data['max_marks'])return back()->withErrors(['marks_obtained'=>'Marks obtained cannot be greater than maximum marks.'])->withInput();$result->update($data);return redirect()->route('admin.results.index')->with('success','Result updated successfully.');}
public function reportCard(Request $request,Student $student,string $exam):View{abort_unless($request->user()->hasPermission('report_cards'),403);$student->load('user');$results=ExamResult::where('student_id',$student->id)->where('exam_name',$exam)->orderBy('subject')->get();abort_if($results->isEmpty(),404);$summary=$this->summary($results);$school=SchoolSetting::first();return view('admin.results.report-card',compact('student','results','exam','school','summary'));}
public function bulkReportCards(Request $request):View{abort_unless($request->user()->hasPermission('report_cards'),403);$data=$request->validate(['exam'=>['required','string','max:150'],'class_name'=>['nullable','string','max:100']]);$studentIds=ExamResult::where('exam_name',$data['exam'])->distinct()->pluck('student_id');$students=Student::with('user')->whereIn('id',$studentIds)->when(!empty($data['class_name']),fn($q)=>$q->where('class_name',$data['class_name']))->orderBy('class_name')->orderBy('section')->orderBy('roll_no')->get();$cards=$students->map(function($student)use($data){$rows=ExamResult::where('student_id',$student->id)->where('exam_name',$data['exam'])->orderBy('subject')->get();return ['student'=>$student,'results'=>$rows,'summary'=>$this->summary($rows)];});abort_if($cards->isEmpty(),404,'No report cards found for the selected filters.');$school=SchoolSetting::first();$exam=$data['exam'];return view('admin.results.bulk-report-cards',compact('cards','school','exam'));}
public function classReport(Request $request):View{abort_unless($request->user()->hasPermission('report_cards'),403);$data=$this->validatedClassReport($request);$report=$this->buildClassReport($data);return view('admin.results.class-report',$report);}
public function classReportExcel(Request $request){abort_unless($request->user()->hasPermission('report_cards'),403);$data=$this->validatedClassReport($request);$report=$this->buildClassReport($data);$safeClass=preg_replace('/[^A-Za-z0-9_-]+/','_',$data['class_name']);$safeExam=preg_replace('/[^A-Za-z0-9_-]+/','_',$data['exam']);$filename="class_result_{$safeClass}_{$safeExam}.xls";return response(view('admin.results.class-report-excel',$report)->render(),200,['Content-Type'=>'application/vnd.ms-excel; charset=UTF-8','Content-Disposition'=>'attachment; filename="'.$filename.'"','Cache-Control'=>'max-age=0']);}
public function destroy(Request $request,ExamResult $result):RedirectResponse{abort_unless($request->user()->hasPermission('results'),403);$result->delete();return back()->with('success','Result deleted successfully.');}
private function validatedResult(Request $request):array{return $request->validate(['student_id'=>['required','exists:students,id'],'exam_name'=>['required','string','max:150'],'subject'=>['required','string','max:150'],'max_marks'=>['required','numeric','min:0.01'],'marks_obtained'=>['required','numeric','min:0'],'exam_date'=>['nullable','date'],'remark'=>['nullable','string','max:255']]);}
private function validatedClassReport(Request $request):array{return $request->validate(['exam'=>['required','string','max:150'],'class_name'=>['required','string','max:100'],'section'=>['nullable','string','max:50']]);}
private function buildClassReport(array $data):array{$students=Student::with('user')->where('class_name',$data['class_name'])->when(!empty($data['section']),fn($q)=>$q->where('section',$data['section']))->whereHas('user')->orderBy('section')->orderByRaw("CASE WHEN roll_no REGEXP '^[0-9]+$' THEN CAST(roll_no AS UNSIGNED) ELSE 999999 END")->orderBy('roll_no')->get();$studentIds=$students->pluck('id');$allResults=ExamResult::whereIn('student_id',$studentIds)->where('exam_name',$data['exam'])->orderBy('subject')->get();$subjects=$allResults->pluck('subject')->unique()->sort()->values();$rows=$students->map(function($student)use($allResults){$results=$allResults->where('student_id',$student->id)->values();if($results->isEmpty())return null;return ['student'=>$student,'results'=>$results->keyBy('subject'),'summary'=>$this->summary($results)];})->filter()->values();abort_if($rows->isEmpty(),404,'No classwise result found for the selected filters.');$school=SchoolSetting::first();return ['rows'=>$rows,'subjects'=>$subjects,'school'=>$school,'exam'=>$data['exam'],'className'=>$data['class_name'],'section'=>$data['section']??null];}
private function summary($results):array{$total=(float)$results->sum(fn($r)=>(float)$r->max_marks);$obtained=(float)$results->sum(fn($r)=>(float)$r->marks_obtained);$percentage=$total>0?round(($obtained/$total)*100,1):0;$grade=$percentage>=90?'A+':($percentage>=80?'A':($percentage>=70?'B+':($percentage>=60?'B':($percentage>=50?'C':($percentage>=40?'D':'F')))));return ['total'=>$total,'obtained'=>$obtained,'percentage'=>$percentage,'grade'=>$grade,'result'=>$percentage>=40?'PASS':'FAIL'];}
}
