<?php
namespace App\Http\Controllers\Admin;
use App\Http\Controllers\Controller;use App\Models\SchoolClass;use App\Models\SchoolSetting;use App\Models\Student;use App\Models\User;use Illuminate\Http\RedirectResponse;use Illuminate\Http\Request;use Illuminate\Support\Facades\DB;use Illuminate\Support\Facades\Hash;use Illuminate\Support\Facades\Storage;use Illuminate\Validation\Rule;use Illuminate\View\View;use Symfony\Component\HttpFoundation\StreamedResponse;
class StudentController extends Controller
{
public function index(Request $request): View {$this->requireStudents($request);$students=$this->scopeForUser(Student::with('user'),$request->user())->latest()->get();$classes=$request->user()->isClassTeacher()?SchoolClass::where('name',$request->user()->assigned_class)->get():SchoolClass::where('is_active',true)->orderBy('sort_order')->orderBy('name')->get();return view('admin.students.index',compact('students','classes'));}
public function classReport(Request $request): View {$this->requireStudents($request);$data=$this->validateClassReport($request);$this->guardTeacherClass($request,$data['class_name'],$data['section']??null);$students=$this->classReportQuery($data)->get();$school=SchoolSetting::first();return view('admin.students.class-report',compact('students','school','data'));}
public function classReportExcel(Request $request): StreamedResponse {$this->requireStudents($request);$data=$this->validateClassReport($request);$this->guardTeacherClass($request,$data['class_name'],$data['section']??null);$students=$this->classReportQuery($data)->get();$filename='students-'.$this->safeFileName($data['class_name']).(!empty($data['section'])?'-'.$this->safeFileName($data['section']):'').'.csv';return response()->streamDownload(function()use($students){$out=fopen('php://output','w');fwrite($out,"\xEF\xBB\xBF");fputcsv($out,['S.No.','Admission No.','Roll No.','Student Name','Class','Section','Gender','Date of Birth','Father Name','Mother Name','Guardian Phone','Status']);foreach($students as $i=>$student){fputcsv($out,[$i+1,$student->admission_no,$student->roll_no,$student->user->name,$student->class_name,$student->section,$student->gender,$student->date_of_birth?->format('d-m-Y'),$student->father_name,$student->mother_name,$student->guardian_phone,$student->is_active?'Active':'Inactive']);}fclose($out);},$filename,['Content-Type'=>'text/csv; charset=UTF-8']);}
public function show(Request $request,Student $student): View {$this->requireStudents($request);$this->guardStudent($request,$student);$student->load('user');return view('admin.students.show',compact('student'));}
public function create(Request $request): View {abort_unless($request->user()->is_admin,403);$classes=SchoolClass::where('is_active',true)->orderBy('sort_order')->orderBy('name')->get();return view('admin.students.form',['student'=>new Student(),'classes'=>$classes]);}
public function store(Request $request): RedirectResponse {abort_unless($request->user()->is_admin,403);$data=$this->validateStudent($request);DB::transaction(function()use($data,$request){$user=User::create(['name'=>$data['name'],'email'=>$data['email'],'password'=>Hash::make($data['password']),'is_admin'=>false]);$studentData=$this->studentData($data);$studentData['user_id']=$user->id;if($request->hasFile('photo'))$studentData['photo']=$request->file('photo')->store('students','public');Student::create($studentData);});return redirect()->route('admin.students.index')->with('success','Student added successfully.');}
public function edit(Request $request,Student $student): View {abort_unless($request->user()->is_admin,403);$student->load('user');$classes=SchoolClass::where('is_active',true)->orderBy('sort_order')->orderBy('name')->get();return view('admin.students.form',compact('student','classes'));}
public function update(Request $request,Student $student): RedirectResponse {abort_unless($request->user()->is_admin,403);$student->load('user');$data=$this->validateStudent($request,$student);DB::transaction(function()use($data,$request,$student){$userData=['name'=>$data['name'],'email'=>$data['email']];if(!empty($data['password']))$userData['password']=Hash::make($data['password']);$student->user->update($userData);$studentData=$this->studentData($data);if($request->hasFile('photo')){if($student->photo)Storage::disk('public')->delete($student->photo);$studentData['photo']=$request->file('photo')->store('students','public');}$student->update($studentData);});return redirect()->route('admin.students.index')->with('success','Student updated successfully.');}
public function toggleStatus(Request $request,Student $student): RedirectResponse {abort_unless($request->user()->is_admin,403);$student->update(['is_active'=>!$student->is_active]);return back()->with('success',$student->is_active?'Student account activated successfully.':'Student account deactivated successfully.');}
private function requireStudents(Request $request):void{abort_unless($request->user()->hasPermission('students'),403);}
private function scopeForUser($query,User $user){if($user->isClassTeacher()){$query->where('class_name',$user->assigned_class);if($user->assigned_section)$query->where('section',$user->assigned_section);}return $query;}
private function guardStudent(Request $request,Student $student):void{$u=$request->user();if($u->isClassTeacher())abort_unless($student->class_name===$u->assigned_class&&(!$u->assigned_section||$student->section===$u->assigned_section),403);}
private function guardTeacherClass(Request $request,string $className,?string $section):void{$u=$request->user();if($u->isClassTeacher())abort_unless($className===$u->assigned_class&&(!$u->assigned_section||$section===$u->assigned_section),403);}
private function validateClassReport(Request $request): array {return $request->validate(['class_name'=>['required','string','max:100'],'section'=>['nullable','string','max:50'],'status'=>['nullable','in:all,active,inactive']]);}
private function classReportQuery(array $data){return Student::with('user')->where('class_name',$data['class_name'])->when(!empty($data['section']),fn($q)=>$q->where('section',$data['section']))->when(($data['status']??'all')==='active',fn($q)=>$q->where('is_active',true))->when(($data['status']??'all')==='inactive',fn($q)=>$q->where('is_active',false))->orderByRaw("CASE WHEN roll_no REGEXP '^[0-9]+$' THEN CAST(roll_no AS UNSIGNED) ELSE 999999 END")->orderBy('roll_no')->orderBy('admission_no');}
private function safeFileName(string $value): string {return preg_replace('/[^A-Za-z0-9_-]+/','-',trim($value));}
private function validateStudent(Request $request,?Student $student=null): array {return $request->validate(['name'=>['required','string','max:255'],'email'=>['required','email','max:255',Rule::unique('users','email')->ignore($student?->user_id)],'password'=>[$student?'nullable':'required','string','min:6'],'admission_no'=>['required','string','max:100',Rule::unique('students','admission_no')->ignore($student?->id)],'class_name'=>['nullable','string','max:100'],'section'=>['nullable','string','max:50'],'roll_no'=>['nullable','string','max:50'],'date_of_birth'=>['nullable','date'],'gender'=>['nullable','string','max:30'],'father_name'=>['nullable','string','max:255'],'mother_name'=>['nullable','string','max:255'],'guardian_name'=>['nullable','string','max:255'],'guardian_phone'=>['nullable','string','max:30'],'address'=>['nullable','string','max:1000'],'photo'=>['nullable','image','mimes:jpg,jpeg,png,webp','max:2048'],'is_active'=>['nullable','boolean']]);}
private function studentData(array $data): array {return ['admission_no'=>$data['admission_no'],'class_name'=>$data['class_name']??null,'section'=>$data['section']??null,'roll_no'=>$data['roll_no']??null,'date_of_birth'=>$data['date_of_birth']??null,'gender'=>$data['gender']??null,'father_name'=>$data['father_name']??null,'mother_name'=>$data['mother_name']??null,'guardian_name'=>$data['guardian_name']??null,'guardian_phone'=>$data['guardian_phone']??null,'address'=>$data['address']??null,'is_active'=>(bool)($data['is_active']??false)];}
}
