<?php
namespace App\Http\Controllers\Admin;
use App\Http\Controllers\Controller;use App\Models\Branch;use App\Models\SchoolSetting;use App\Models\Student;use App\Models\StudentDocument;use Illuminate\Http\RedirectResponse;use Illuminate\Http\Request;use Illuminate\Support\Facades\Storage;use Illuminate\View\View;
class StudentDocumentController extends Controller
{
public function index(Request $request):View{abort_unless($request->user()->hasPermission('certificates'),403);$user=$request->user();$search=trim((string)$request->query('q',''));$studentQuery=Student::with(['user','branch'])->where('is_active',true);if(!$user->is_admin&&$user->branch_id)$studentQuery->where('branch_id',$user->branch_id);if($user->isClassTeacher()){$studentQuery->where('class_name',$user->assigned_class);if($user->assigned_section)$studentQuery->where('section',$user->assigned_section);}if($user->is_admin&&$request->filled('branch_id'))$studentQuery->where('branch_id',$request->integer('branch_id'));if($search!==''){$studentQuery->where(function($q)use($search){$q->where('admission_no','like','%'.$search.'%')->orWhereHas('user',fn($userQuery)=>$userQuery->where('name','like','%'.$search.'%'));});}$students=$studentQuery->orderBy('admission_no')->get();$documents=StudentDocument::with(['student.user','student.branch'])->whereIn('student_id',$students->pluck('id'))->latest('id')->get();$branches=$user->is_admin?Branch::where('is_active',true)->orderByDesc('is_main')->orderBy('name')->get():Branch::whereKey($user->branch_id)->get();return view('admin.documents.index',compact('students','documents','branches','search'));}
public function generate(Request $request):View{abort_unless($request->user()->hasPermission('certificates'),403);$data=$request->validate(['student_id'=>['required','exists:students,id'],'certificate_type'=>['required','in:bonafide,character,study'],'purpose'=>['nullable','string','max:255']]);$student=Student::with(['user','branch'])->findOrFail($data['student_id']);$this->guardStudent($request,$student);$school=SchoolSetting::first();$type=$data['certificate_type'];$purpose=trim($data['purpose']??'');return view('admin.documents.certificate',compact('student','school','type','purpose'));}
public function store(Request $request):RedirectResponse{abort_unless($request->user()->is_admin,403);$data=$request->validate(['student_id'=>['required','exists:students,id'],'title'=>['required','string','max:150'],'document_type'=>['required','string','max:100'],'document'=>['required','file','mimes:pdf,jpg,jpeg,png','max:5120'],'note'=>['nullable','string','max:255']]);$data['file_path']=$request->file('document')->store('student-documents','public');unset($data['document']);StudentDocument::create($data);return back()->with('success','Document uploaded successfully.');}
public function destroy(Request $request,StudentDocument $document):RedirectResponse{abort_unless($request->user()->is_admin,403);if($document->file_path)Storage::disk('public')->delete($document->file_path);$document->delete();return back()->with('success','Document deleted successfully.');}
private function guardStudent(Request $request,Student $student):void{$user=$request->user();if(!$user->is_admin&&$user->branch_id)abort_unless((int)$student->branch_id===(int)$user->branch_id,403);if($user->isClassTeacher())abort_unless($student->class_name===$user->assigned_class&&(!$user->assigned_section||$student->section===$user->assigned_section),403);}
}
